### ISSUE TITLE
linking zkt-ls fails with undefinced references

### ISSUE THREAD

**Issue by tru7** [hzuleger/ZKT#4]
Using gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4. Linking zkt-ls fails with:
gcc  -lncurses  zkt-ls.o strlist.o zkt.o tcap.o dki.o misc.o domaincmp.o zconf.o log.o -o zkt-ls
tcap.o: In function `tc_init':
/scratch/zkt/tcap.c:103: undefined reference to `tgetent'

But works fine when putting -lncurses at the end of line:
gcc zkt-ls.o strlist.o zkt.o tcap.o dki.o misc.o domaincmp.o zconf.o log.o -o zkt-ls -lncurses

Couldn't that be just changed in Makefile.in?

**Comment by hzuleger** [comment]
Done

**Comment by tru7** [comment]
thank you
